#!/bin/bash

set -ex

export PATH=$PATH:/snap/bin

kubectl --kubeconfig=/root/cdk/config cordon $(hostname)
kubectl --kubeconfig=/root/cdk/config drain $(hostname) --force
status-set 'waiting' 'Kubernetes unit paused'
